import {
  sectorCommunicationImage,
  sectorEnergyImage,
  sectorHealthImage,
  sectorTransportImage,
  sectorUrbanImage,
  sectorWaterImage,
} from '../assets'

export const sectorHighlights = [
  { icon: 'government', label: 'Sector-wise project analysis', tone: 'orange' },
  { icon: 'trend', label: 'Comparative insights across states', tone: 'blue' },
  { icon: 'shieldCheck', label: 'Track key projects and milestones', tone: 'green' },
  { icon: 'clock', label: 'Identify delays and potential risks', tone: 'purple' },
]

export const featuredSectors = [
  {
    name: 'Transport & Logistics',
    description: 'Roads, highways, railways, ports, airports and more.',
    image: sectorTransportImage,
    icon: 'truck',
    tone: 'orange',
    projects: 350,
    onTrack: 238,
    atRisk: 72,
    delayed: 40,
  },
  {
    name: 'Energy',
    description: 'Power generation, transmission, renewable energy and more.',
    image: sectorEnergyImage,
    icon: 'bolt',
    tone: 'blue',
    projects: 290,
    onTrack: 180,
    atRisk: 70,
    delayed: 40,
  },
  {
    name: 'Water & Sanitation',
    description: 'Drinking water supply, sewage treatment, irrigation and more.',
    image: sectorWaterImage,
    icon: 'drop',
    tone: 'blue',
    projects: 210,
    onTrack: 122,
    atRisk: 54,
    delayed: 34,
  },
  {
    name: 'Communication',
    description: 'Telecom, digital infrastructure and connectivity.',
    image: sectorCommunicationImage,
    icon: 'signal',
    tone: 'purple',
    projects: 152,
    onTrack: 110,
    atRisk: 28,
    delayed: 14,
  },
  {
    name: 'Urban Infrastructure',
    description: 'Cities, public spaces, transit and civic services.',
    image: sectorUrbanImage,
    icon: 'government',
    tone: 'green',
    projects: 240,
    onTrack: 170,
    atRisk: 48,
    delayed: 22,
  },
  {
    name: 'Health',
    description: 'Hospitals, medical facilities and public health systems.',
    image: sectorHealthImage,
    icon: 'shieldCheck',
    tone: 'purple',
    projects: 190,
    onTrack: 135,
    atRisk: 38,
    delayed: 17,
  },
]

export const allSectorNames = [
  'Transport & Logistics',
  'Energy',
  'Water & Sanitation',
  'Communication',
  'Urban Infrastructure',
  'Health',
  'Education',
  'Housing',
  'Agriculture',
  'Irrigation',
  'Railways',
  'Roads & Highways',
  'Ports & Shipping',
  'Civil Aviation',
  'Petroleum & Natural Gas',
  'Mining',
  'Steel',
  'Coal',
  'Tourism',
  'Digital Infrastructure',
  'Social Infrastructure',
  'Industrial Corridors',
]
